// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = (import.meta.env?.VITE_SUPABASE_URL || 'https://placeholder.supabase.co') as string;
const supabaseAnonKey = (import.meta.env?.VITE_SUPABASE_ANON_KEY || 'placeholder-anon-key') as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);